title: Carriage Houses
description: A hobby garage condo community
url: "https://carriagehouseskc.com"
baseurl: ""

# Build settings
markdown: kramdown
permalink: pretty

collections:
  newsletters:
    output: true
    permalink: /newsletter/:name/

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
